[package]
name = "reading"
version = "0.2.0"
authors = ["Ian Johnson <ianprime0509@gmail.com>"]

[dependencies]
ansi_term = "0.9"
app_dirs = "1.1.1"
clap = "2.19.2"
error-chain = "0.10.0"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
